#2 stn network lambda layer
x= keras.layers.Lambda(_transform,
                           output_shape=stn_input_output_shape)([x, localization_net(x)]) 레이어에서 미지원 함수로 에러남. 
node lambda/AddN of type AddN cannot be converted, fall back to tf2onnx
Traceback (most recent call last):
  File "build_model.py", line 66, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/main.py", line 60, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 794, in parse_graph
    graph, keras_node_dict, topo, top_level, output_names)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 595, in _parse_graph_core
    _on_parsing_tf_subgraph(graph, nodes, varset)
  File "/usr/local/lib/python3.6/dist-packages/keras2onnx/parser.py", line 335, in _on_parsing_tf_subgraph
    raise RuntimeError("Some tensorflow operation doesn't support, stop converting.")
RuntimeError: Some tensorflow operation doesn't support, stop converting.